# Generated by Django 4.1.5 on 2023-01-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
