# Generated by Django 4.1.5 on 2023-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_hiaceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiace',
            name='selected_seats',
            field=models.TextField(default=''),
        ),
    ]
