# Generated by Django 4.1.5 on 2023-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hiace_selected_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiace',
            name='selected_seats',
        ),
        migrations.AddField(
            model_name='book',
            name='selected_seats',
            field=models.TextField(default=''),
        ),
    ]
