# Generated by Django 4.1.5 on 2023-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_hiace_selected_seats_book_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiace',
            name='selected_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
