# Generated by Django 4.1.5 on 2023-01-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hiace_selected_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiace',
            name='selected_seats',
        ),
    ]
