# Generated by Django 4.1.5 on 2023-01-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_hiace_selected_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='selected_seats',
        ),
    ]
