# Generated by Django 4.1.5 on 2023-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_book_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seat_name',
            field=models.TextField(null=True),
        ),
    ]
