# Generated by Django 4.1.5 on 2023-02-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_seat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='seat_name',
            new_name='name_seats',
        ),
    ]
