# Generated by Django 4.1.5 on 2023-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_seat_name_book_name_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiace',
            name='name_seats',
            field=models.TextField(null=True),
        ),
    ]
