# Generated by Django 4.1.5 on 2023-02-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hiace_name_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hiace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hiace'),
        ),
    ]
